### ISSUE TITLE
Problem with device token list

### ISSUE THREAD

**Issue by arnobo** [ZsoltSafrany/java-apns-gae#4]
Hello,
First, thanks for your library.
I'm able to send a notification to a list containing one device token using the samples given on your website. I tried with and without the queue, in both cases it is working fine with one device token.

But when I use a bigger list (I have 15-20 users), nothing appens. It seems only one device receives the notification but I don't have any exception.

Do you have any idea of what could be the problem ? A socket connection closing ?
For information, I use GAE 1.9.21 and java-apns-gae 1.2

Thanks

**Comment by ZsoltSafrany** [comment]
Hey,

thank you for reporting the issue. It is a known one and got fixed recently with 94f9a508495056107276cc53ff928dcb303709f8.

**Comment by arnobo** [comment]
Hello, 
thanks for your response. I'm sorry I tried with the new version but it is worst: no notification received on any device. Logs seems fine but nothing happened

**Comment by ZsoltSafrany** [comment]
Hey, thanks for letting me know! I'm gonna double check this in #3...

**Comment by ZsoltSafrany** [comment]
@arnobo, could you please double-check whether the problem really exists? @kostadinstoilov just said in #3 that he tested it and using it in production.

**Comment by arnobo** [comment]
Hi,
I don't know why but now it seems working. I just redeployed my server and set it as "default version" in GAE console.
Thanks for your help !

**Comment by ZsoltSafrany** [comment]
Awesome, thanks for double-checking!
